### PR TITLE
Fix for Folder not displaying and Tag insensitivity

### LINKED ISSUE #302: [PE-D][Tester E] Tag Folder Never Returns Until Restart
1. Steps:
   1)add n/Test p/123 e/test@test a/Addr t/VIP → sidebar shows VIP.
   2)delete <that contact> → folder disappears.
   3)add n/Another p/456 e/another@test a/Addr t/VIP.

2. Expected: The VIP folder is recreated automatically.

3. Actual: No folder appears. When the last VIP entry was removed, refreshActiveTagFolderCounts deleted the folder but left the folderIndex cache untouched (src/main/java/seedu/address/model/ModelManager.java (lines 364-378)). Later, ensureFoldersExistForTags checks the stale cache (src/main/java/seedu/address/model/ModelManager.java (lines 456-466)) and wrongly believes the folder still exists, so it never re-adds it. Restarting the app rebuilds the cache, which is why it comes back only then.

4. Evidence:

Image
Image
Image 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Huffle-Buffle**
Fix for #252 
Fix #302

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -458,14 +462,17 @@ private void ensureFoldersExistForTags(java.util.Collection<? extends seedu.addr
         if (tags == null) {
             return;
         }
+        boolean added = false;
         for (seedu.address.model.tag.Tag t : tags) {
```
Comment (LZX-999) [inline src/main/java/seedu/address/model/ModelManager.java]: Please import it don't use fully qualified name
